version: "2"
services:
    db:
        image: postgres
        container_name: open_elections_peru_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - /usr/lib/postgresql
            - .:/usr/app/
    web: &web
        build: .
        container_name: open_elections_peru_web
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/app
        working_dir: /usr/app
        links:
            - db:db
            - redis:redis
        environment:
            PYTHONPATH: /usr/app/project
            DJANGO_SETTINGS_MODULE: project.settings.local
            SHELL: /bin/bash
    redis:
        image: redis:latest
        container_name: open_elections_peru_redis
        restart: always
        ports:
            - "6379:6379"
