# Generated by Django 3.1.7 on 2021-03-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jne_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Election Type',
                'verbose_name_plural': 'Election Types',
            },
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ubigeo', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'Electoral District',
                'verbose_name_plural': 'Electoral Districts',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('second_surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_address', models.CharField(max_length=255)),
                ('birth_country', models.CharField(max_length=50)),
                ('birth_department', models.CharField(max_length=50)),
                ('birth_province', models.CharField(max_length=50)),
                ('birth_district', models.CharField(max_length=50)),
                ('birth_ubigeo', models.CharField(max_length=6)),
                ('dni', models.CharField(db_index=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('', ''), ('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jne_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Political Organization',
                'verbose_name_plural': 'Political Organizations',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jne_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('call_date', models.DateField(null=True)),
                ('registration_date', models.DateField(null=True)),
                ('opening_date', models.DateField(null=True)),
                ('closing_date', models.DateField(null=True)),
                ('jne_id', models.BigIntegerField(unique=True)),
                ('districts', models.ManyToManyField(to='app_elections.ElectoralDistrict')),
                ('election_types', models.ManyToManyField(to='app_elections.ElectionType')),
                ('positions', models.ManyToManyField(to='app_elections.Position')),
            ],
            options={
                'verbose_name': 'Election Process',
                'verbose_name_plural': 'Election Processes',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_position', models.PositiveSmallIntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('residence_address', models.CharField(max_length=255)),
                ('residence_department', models.CharField(max_length=50)),
                ('residence_province', models.CharField(max_length=50)),
                ('residence_district', models.CharField(max_length=50)),
                ('residence_ubigeo', models.CharField(max_length=6)),
                ('status_on_list', models.CharField(db_index=True, max_length=20)),
                ('jne_id', models.BigIntegerField(unique=True)),
                ('photo_url_path', models.CharField(max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='app_elections.electionprocess')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_elections.electiontype')),
                ('electoral_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_elections.electoraldistrict')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_elections.person')),
                ('political_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_elections.politicalorganization')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_elections.position')),
            ],
        ),
    ]
